CREATE DATABASE integration_test;
GRANT ALL PRIVILEGES ON DATABASE integration_test TO star;
CREATE DATABASE slow;
GRANT ALL PRIVILEGES ON DATABASE slow TO star;
CREATE DATABASE express;
GRANT ALL PRIVILEGES ON DATABASE express TO star;
